### ISSUE TITLE
Clarify valid filenames

### ISSUE THREAD

**Issue by 2641a40fd44383320adde4b027a1d0b03bd550** [MrOtherGuy/fx-autoconfig#31]
I got the following error for filename `_replace-window-title.uc.js`, but not `replace-window-title.uc.js`:
```
Error: @ _replace-window-title.uc.js:undefined
    tryLoadIntoWindow chrome://userchromejs/content/boot.jsm:154
    onDOMContent chrome://userchromejs/content/boot.jsm:811
    handleEvent chrome://userchromejs/content/boot.jsm:870
Caused by: "Error opening input stream (invalid filename?): chrome://userscripts/content/_replace-window-title.uc.js"
```

**Comment by MrOtherGuy** [comment]
This is actually more interesting than I thought it would be.

The loader handles the file just fine. However, it seems there is a restriction with `chrome:` resolution such that the path must always start with `[a-zA-Z0-9]` [per searchfox](https://searchfox.org/mozilla-central/rev/3c7b40d1d74c26a82486f38b5828c3f3a43e05da/chrome/nsChromeRegistry.cpp#207)

Note that just the top-level path must start with with alpanumeric characters - if your file would be in a sub-folder then starting its name with an underscore works fine. Of course, then the loader won't find it, but the chrome uri resolver doesn't restrict the filename in such case.

Also, since it is about Firefox internal chrome uri resolution this same limitation affects other resources as well. So, if you were to say, create a file `_icon.png` in the resources directory, then you cannot use with chrome url - so this won't work:

```css
#preferences-button{
  list-style-image: url("chrome://userchrome/content/_icon.png") !important;
}
```

But if you move the file into a sub-folder then it works fine:

```css
#preferences-button{
  list-style-image: url("chrome://userchrome/content/newdir/_icon.png") !important;
}
```

I'm not sure how I should handle this. I could just completely ignore all scripts that don't start with `[a-zA-Z0-9]` or I could potentially just not load them and instead give show a clear error that loading a file with this name won't work. That sounds neat, but then I would give such a warning for *every* non-matching file - not just those starting with an underscore.
