### ISSUE TITLE
Where should I put the image file to load in CSS

### ISSUE THREAD

**Issue by alixTal** [MrOtherGuy/fx-autoconfig#47]
Hi, I'm trying to change an extension icon, I put my icon in CSS folder, but it won't load the image 

this is the CSS:
```css
#_3c078156-979c-498b-8990-85f7987dd929_-BAP {
  --webextension-toolbar-image-light: url("icon.svg") !important;
}
```

When I check the inspector, it's showing the image path as this `chrome://userstyles/skin/icon.svg`
where should I put the image in order to Firefox can load it?
