### ISSUE TITLE
Compatibility with Zen

### ISSUE THREAD

**Issue by rubaboo** [MrOtherGuy/fx-autoconfig#60]
Everything works, except there  is no "userScripts" menu, since there is no Tools menu in Zen. The entire Zen menu is under ellipsis button. Could you make "userScripts" appear there, or provide a workaround (userChrome?).

<img src="https://github.com/user-attachments/assets/85ea857e-d158-4b34-99bf-c51bb8a52ae8" width="30%"></img>

**Comment by MrOtherGuy** [comment]
I've been meaning to look into that anyway, because macos doesn't even have a menubar. It's just that it's a non-trivial change because it's very straightforward to add a `<menu>` + `<menupopup>` but not so much to add a panel view item and a subview for it. It probably isn't *that* hard, but it is compared to menupopup.

**Comment by rubaboo** [comment]
Not that you need my help @MrOtherGuy 😀, but I managed to roughly put something together, and I'm liking the result.
I unhid the original Firefox menu (that is still there in Zen) and moved it to navbar.

<img src="https://github.com/user-attachments/assets/3d4be5c9-e632-4fa4-b64a-dde5ef29cf83"></img>

It's not a finished userscript, but a pref + some usercss + code pasted into console.

```css
#toolbar-menubar {
  display: revert !important;
}
#toolbar-menubar {
  &[autohide="true"] {
    &[inactive]:not([customizing]) {
      height: auto !important;
	}
  }
  & > .titlebar-buttonbox-container {
    visibility: collapse;
  }
}
```
```javascript
let parent = document.getElementById('zen-appcontent-navbar-container');
let target = document.getElementById('toolbar-menubar');
parent.appendChild(target);
```
